import { copyFile, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import app from "../examples/tasks/app.js";
import { compileApp } from "../src/compiler.js";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

export async function build() {
  const output = join(root, "dist");
  const runtimeOutput = join(output, "runtime");
  const styles = await readFile(join(root, "examples/tasks/styles.css"), "utf8");
  const result = compileApp(app, {
    styles,
    runtimeImport: "./runtime/browser.js",
  });

  await rm(output, { recursive: true, force: true });
  await mkdir(runtimeOutput, { recursive: true });
  await Promise.all([
    writeFile(join(output, "index.html"), result.html),
    writeFile(join(output, "app.js"), result.module),
    writeFile(join(output, "plan.json"), JSON.stringify(result.plan, null, 2)),
    copyFile(join(root, "src/runtime/browser.js"), join(runtimeOutput, "browser.js")),
    copyFile(join(root, "src/runtime/engine.js"), join(runtimeOutput, "engine.js")),
  ]);

  return {
    output,
    htmlBytes: Buffer.byteLength(result.html),
    moduleBytes: Buffer.byteLength(result.module),
    bindings: result.plan.bindings.length,
    routes: Object.keys(result.plan.eventRoutes).length,
  };
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(resolve(process.argv[1])).href
) {
  const result = await build();
  console.log(
    `Built ${result.output} · ${result.bindings} bindings · ${result.routes} event routes · ${result.htmlBytes + result.moduleBytes} generated bytes`,
  );
}
